workspace:
  base: /drone
  path: src/${DRONE_REPO_NAME}

clone:
  default:
    image: plugins/git
    recursive: true
    group: clone

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
      - ./.yarn-cache
    volumes:
      - /tmp/cache:/cache

  build:
    image: presslabs/particles-build
    pull: true
    commands:
      - Xvfb :1 -screen 0 800x600x16 &
      - make build

  # copy-demo:
  #   image: alpine:3.7
  #   commands:
  #     - mkdir -p /drone/src/presslabs-org/wp-content/root/particles/
  #     - rm -rf /drone/src/presslabs-org/wp-content/root/particles/*
  #     - mv demo/* /drone/src/presslabs-org/wp-content/root/particles
  #   when:
  #     branch: master
  #     event: push
  #
  # update-presslabs-org:
  #   image: appleboy/drone-git-push
  #   branch: prod
  #   commit: true
  #   path: /drone/src/presslabs-org
  #   commit_message: "[particles] Update particles demo"
  #   remote: git@github.com:/Presslabs/presslabs-org.git
  #   secrets:
  #     - GIT_PUSH_SSH_KEY
  #   when:
  #     branch: master
  #     event: push

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - ./.yarn-cache
    volumes:
      - /tmp/cache:/cache

  npm:
    image: plugins/npm
    email: support@presslabs.com
    secrets: [ npm_username, npm_password ]
    when:
      branch: master
      event: push
