pipeline:
  build:
    image: presslabs/particles-build
    commands:
      - make build
      - make github-pages

  github_pages:
    image: appleboy/drone-git-push
    force: true
    branch: gh-pages
    remote: git@github.com:/Presslabs/particles.git
    secrets:
      - GIT_PUSH_SSH_KEY
    commit_message: "Update static page"
    when:
      branch: master

  npm:
    image: plugins/npm
    username: $NPM_USERNAME
    password: $NPM_PASSWORD
    email: support@presslabs.com
    secrets: [ npm_username, npm_password ]
    when:
      branch: master

  trigger:
    image: plugins/downstream
    server: https://drone.presslabs.net
    fork: true
    secrets: [ downstream_token ]
    repositories:
       - PressLabs/react-particles-icons
    when:
      branch: master
